/////////////////////////////////////////////////////////////////////////////
// Name:        itkconfidenceconnectedfilter.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     14/08/2007 13:04:00
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 14/08/2007 13:04:00

#ifndef _ITKCONFIDENCECONNECTEDFILTER_H_
#define _ITKCONFIDENCECONNECTEDFILTER_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
#include "wx/spinctrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxSpinCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_ITKCONFIDENCECONNECTEDFILTER 10012
#define SYMBOL_ITKCONFIDENCECONNECTEDFILTER_STYLE 0
#define SYMBOL_ITKCONFIDENCECONNECTEDFILTER_TITLE _("ITKConfidenceConnectedFilter")
#define SYMBOL_ITKCONFIDENCECONNECTEDFILTER_IDNAME ID_ITKCONFIDENCECONNECTEDFILTER
#define SYMBOL_ITKCONFIDENCECONNECTEDFILTER_SIZE wxSize(200, -1)
#define SYMBOL_ITKCONFIDENCECONNECTEDFILTER_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ITKConfidenceConnectedFilter class declaration
 */

class ITKConfidenceConnectedFilter: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( ITKConfidenceConnectedFilter )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ITKConfidenceConnectedFilter();
    ITKConfidenceConnectedFilter( wxWindow* parent, wxWindowID id = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_IDNAME, const wxPoint& pos = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_POSITION, const wxSize& size = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_SIZE, long style = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_IDNAME, const wxPoint& pos = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_POSITION, const wxSize& size = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_SIZE, long style = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_STYLE );

    /// Destructor
    ~ITKConfidenceConnectedFilter();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();
	void OnClearSeedsButtonClick( wxCommandEvent& event );
	void OnStartButtonClick( wxCommandEvent& event );
	void OnStopButtonClick( wxCommandEvent& event );
	void OnCloseButtonClick( wxCommandEvent& event );
	void OnSetProgress( wxCommandEvent& event );

////@begin ITKConfidenceConnectedFilter event handler declarations

////@end ITKConfidenceConnectedFilter event handler declarations

////@begin ITKConfidenceConnectedFilter member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ITKConfidenceConnectedFilter member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ITKConfidenceConnectedFilter member variables
    wxSpinCtrl* mIterations;
    wxSpinCtrl* mMultipliers;
    wxGauge* mPercentage;
////@end ITKConfidenceConnectedFilter member variables

    wxWindowDisabler *disabler_;
};

#endif
    // _ITKCONFIDENCECONNECTEDFILTER_H_
