/////////////////////////////////////////////////////////////////////////////
// Name:        itkthresholdsegmentationlevelsetfilter.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     14/08/2007 13:09:41
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 14/08/2007 13:09:41

#ifndef _ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_H_
#define _ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
#include "wx/spinctrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxSpinCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER 10013
#define SYMBOL_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_STYLE 0
#define SYMBOL_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_TITLE _("ITKThresholdSegmentationLevelSetFilter")
#define SYMBOL_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_IDNAME ID_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER
#define SYMBOL_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_SIZE wxSize(200, -1)
#define SYMBOL_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ITKThresholdSegmentationLevelSetFilter class declaration
 */

class ITKThresholdSegmentationLevelSetFilter: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( ITKThresholdSegmentationLevelSetFilter )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ITKThresholdSegmentationLevelSetFilter();
    ITKThresholdSegmentationLevelSetFilter( wxWindow* parent, wxWindowID id = SYMBOL_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_IDNAME, const wxPoint& pos = SYMBOL_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_POSITION, const wxSize& size = SYMBOL_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_SIZE, long style = SYMBOL_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_IDNAME, const wxPoint& pos = SYMBOL_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_POSITION, const wxSize& size = SYMBOL_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_SIZE, long style = SYMBOL_ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_STYLE );

    /// Destructor
    ~ITKThresholdSegmentationLevelSetFilter();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

	void OnSetSeedLayerButtonClick( wxCommandEvent& event );
	void OnSetDataLayerButtonClick( wxCommandEvent& event );
	void OnStartButtonClick( wxCommandEvent& event );
	void OnStopButtonClick( wxCommandEvent& event );
	void OnCloseButtonClick( wxCommandEvent& event );
	void OnSetProgress( wxCommandEvent& event );

    void SpinRadius( wxSpinEvent &event);
    void UpdateRadius( wxCommandEvent &event);

////@begin ITKThresholdSegmentationLevelSetFilter event handler declarations

////@end ITKThresholdSegmentationLevelSetFilter event handler declarations


////@begin ITKThresholdSegmentationLevelSetFilter member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ITKThresholdSegmentationLevelSetFilter member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ITKThresholdSegmentationLevelSetFilter member variables
    wxSpinCtrl* mRadius;
    wxSpinCtrl* mThresholdMin;
    wxSpinCtrl* mThresholdMax;
    wxSpinCtrl* mCurvatureScale;
    wxSpinCtrl* mPropagationScale;
    wxSpinCtrl* mEdgeWeight;
    wxGauge* mPercentage;
////@end ITKThresholdSegmentationLevelSetFilter member variables

    wxWindowDisabler *disabler_;
};

#endif
    // _ITKTHRESHOLDSEGMENTATIONLEVELSETFILTER_H_
