/////////////////////////////////////////////////////////////////////////////
// Name:        cropvolcylinder.cpp
// Purpose:     
// Author:      
// Modified by: 
// Created:     20/08/2007 08:51:42
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 20/08/2007 08:51:42

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"
#include <StandAlone/Apps/Seg3D/Painter.h>

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "cropvolcylinder.h"
#include "seg3devents.h"

////@begin XPM images
////@end XPM images


/*!
 * CropVolCylinder type definition
 */

IMPLEMENT_DYNAMIC_CLASS( CropVolCylinder, wxPanel )


/*!
 * CropVolCylinder event table definition
 */

BEGIN_EVENT_TABLE( CropVolCylinder, wxPanel )

////@begin CropVolCylinder event table entries
////@end CropVolCylinder event table entries
    EVT_BUTTON( XRCID("START_BUTTON"), CropVolCylinder::OnStartButtonClick )
    EVT_BUTTON( XRCID("CLOSE_BUTTON"), CropVolCylinder::OnCloseButtonClick )
    EVT_COMMAND (wxID_ANY, wxEVT_CROP_SET_MINMAX, CropVolCylinder::OnCropSetMinMax )
    EVT_COMMAND (wxID_ANY, wxEVT_CROP_SET_RANGE, CropVolCylinder::OnCropSetRange )
    EVT_SPINCTRL( XRCID("SPIN_MIN_X"), CropVolCylinder::OnSpinMinX)
    EVT_SPINCTRL( XRCID("SPIN_MAX_X"), CropVolCylinder::OnSpinMaxX)
    EVT_SPINCTRL( XRCID("SPIN_MIN_Y"), CropVolCylinder::OnSpinMinY)
    EVT_SPINCTRL( XRCID("SPIN_MAX_Y"), CropVolCylinder::OnSpinMaxY)
    EVT_SPINCTRL( XRCID("SPIN_MIN_Z"), CropVolCylinder::OnSpinMinZ)
    EVT_SPINCTRL( XRCID("SPIN_MAX_Z"), CropVolCylinder::OnSpinMaxZ)

END_EVENT_TABLE()


/*!
 * CropVolCylinder constructors
 */

CropVolCylinder::CropVolCylinder()
{
    Init();
}

CropVolCylinder::CropVolCylinder( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, pos, size, style);
}


/*!
 * CropVolCylinder creator
 */

bool CropVolCylinder::Create( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
////@begin CropVolCylinder creation
    SetParent(parent);
    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
////@end CropVolCylinder creation
    return true;
}


/*!
 * CropVolCylinder destructor
 */

CropVolCylinder::~CropVolCylinder()
{
////@begin CropVolCylinder destruction
////@end CropVolCylinder destruction
}


/*!
 * Member initialisation
 */

void CropVolCylinder::Init()
{
////@begin CropVolCylinder member initialisation
    mSpinMinX = NULL;
    mSpinMaxX = NULL;
    mSpinMinY = NULL;
    mSpinMaxY = NULL;
    mSpinMinZ = NULL;
    mSpinMaxZ = NULL;
////@end CropVolCylinder member initialisation
}


/*!
 * Control creation for CropVolCylinder
 */

void CropVolCylinder::CreateControls()
{    
////@begin CropVolCylinder content construction
    if (!wxXmlResource::Get()->LoadPanel(this, GetParent(), _T("ID_CROPVOLCYLINDER")))
        wxLogError(wxT("Missing wxXmlResource::Get()->Load() in OnInit()?"));
    mSpinMinX = XRCCTRL(*this, "SPIN_MIN_X", wxSpinCtrl);
    mSpinMaxX = XRCCTRL(*this, "SPIN_MAX_X", wxSpinCtrl);
    mSpinMinY = XRCCTRL(*this, "SPIN_MIN_Y", wxSpinCtrl);
    mSpinMaxY = XRCCTRL(*this, "SPIN_MAX_Y", wxSpinCtrl);
    mSpinMinZ = XRCCTRL(*this, "SPIN_MIN_Z", wxSpinCtrl);
    mSpinMaxZ = XRCCTRL(*this, "SPIN_MAX_Z", wxSpinCtrl);
////@end CropVolCylinder content construction

    // Set up a reasonable default range.
    mSpinMinX->SetRange(0, 0x7fffffff);
    mSpinMinY->SetRange(0, 0x7fffffff);
    mSpinMinZ->SetRange(0, 0x7fffffff);
    mSpinMaxX->SetRange(1, 0x7fffffff);
    mSpinMaxY->SetRange(1, 0x7fffffff);
    mSpinMaxZ->SetRange(1, 0x7fffffff);

    // Create custom windows not generated automatically here.
////@begin CropVolCylinder content initialisation
////@end CropVolCylinder content initialisation
}

void CropVolCylinder::OnCropSetMinMax( wxCommandEvent &event )
{
    CropVolCylinderSetRangeStruct *csrs = (CropVolCylinderSetRangeStruct *)event.GetClientData();
    mSpinMinX->SetValue(csrs->min_x);
    mSpinMinY->SetValue(csrs->min_y);
    mSpinMinZ->SetValue(csrs->min_z);
    mSpinMaxX->SetValue(csrs->max_x);
    mSpinMaxY->SetValue(csrs->max_y);
    mSpinMaxZ->SetValue(csrs->max_z);
}


void CropVolCylinder::OnCropSetRange( wxCommandEvent &event )
{
  CropVolCylinderSetRangeStruct *csrs = (CropVolCylinderSetRangeStruct *)event.GetClientData();

  mSpinMinX->SetRange(0, csrs->min_x);
  mSpinMinY->SetRange(0, csrs->min_y);
  mSpinMinZ->SetRange(0, csrs->min_z);
  mSpinMaxX->SetRange(1, csrs->max_x);
  mSpinMaxY->SetRange(1, csrs->max_y);
  mSpinMaxZ->SetRange(1, csrs->max_z);
}

void CropVolCylinder::OnSpinMinX( wxSpinEvent &event )
{
  SCIRun::ThrowSkinnerSignalEvent *tsse =
    new SCIRun::ThrowSkinnerSignalEvent("Painter::RedrawAll");
  tsse->add_var("Painter::crop::min::x",
                SCIRun::to_string(event.GetPosition()));
  SCIRun::Painter::ThrowSkinnerSignal(tsse);
}

void CropVolCylinder::OnSpinMaxX( wxSpinEvent &event )
{
  SCIRun::ThrowSkinnerSignalEvent *tsse =
    new SCIRun::ThrowSkinnerSignalEvent("Painter::RedrawAll");
  tsse->add_var("Painter::crop::max::x",
                SCIRun::to_string(event.GetPosition()));
  SCIRun::Painter::ThrowSkinnerSignal(tsse);
}

void CropVolCylinder::OnSpinMinY( wxSpinEvent &event )
{
  SCIRun::ThrowSkinnerSignalEvent *tsse =
    new SCIRun::ThrowSkinnerSignalEvent("Painter::RedrawAll");
  tsse->add_var("Painter::crop::min::y",
                SCIRun::to_string(event.GetPosition()));
  SCIRun::Painter::ThrowSkinnerSignal(tsse);
}

void CropVolCylinder::OnSpinMaxY( wxSpinEvent &event )
{
  SCIRun::ThrowSkinnerSignalEvent *tsse =
    new SCIRun::ThrowSkinnerSignalEvent("Painter::RedrawAll");
  tsse->add_var("Painter::crop::max::y",
                SCIRun::to_string(event.GetPosition()));
  SCIRun::Painter::ThrowSkinnerSignal(tsse);
}

void CropVolCylinder::OnSpinMinZ( wxSpinEvent &event )
{
  SCIRun::ThrowSkinnerSignalEvent *tsse =
    new SCIRun::ThrowSkinnerSignalEvent("Painter::RedrawAll");
  tsse->add_var("Painter::crop::min::z",
                SCIRun::to_string(event.GetPosition()));
  SCIRun::Painter::ThrowSkinnerSignal(tsse);
}

void CropVolCylinder::OnSpinMaxZ( wxSpinEvent &event )
{
  SCIRun::ThrowSkinnerSignalEvent *tsse =
    new SCIRun::ThrowSkinnerSignalEvent("Painter::RedrawAll");
  tsse->add_var("Painter::crop::max::z",
                SCIRun::to_string(event.GetPosition()));
  SCIRun::Painter::ThrowSkinnerSignal(tsse);
}

/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for START_BUTTON
 */
void CropVolCylinder::OnStartButtonClick( wxCommandEvent& event )
{
  wxBeginBusyCursor();
  SCIRun::Painter::ThrowSkinnerSignal("Painter::FinishTool");
  wxEndBusyCursor();

  SCIRun::Painter::global_seg3dframe_pointer_->HideTool();
}

/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for CLOSE_BUTTON
 */
void CropVolCylinder::OnCloseButtonClick( wxCommandEvent& event )
{
  SCIRun::Painter::global_seg3dframe_pointer_->HideTool();
}

/*!
 * Should we show tooltips?
 */

bool CropVolCylinder::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap CropVolCylinder::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin CropVolCylinder bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end CropVolCylinder bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon CropVolCylinder::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin CropVolCylinder icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end CropVolCylinder icon retrieval
}
