/////////////////////////////////////////////////////////////////////////////
// Name:        fliptool.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     27/08/2007 09:39:40
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 27/08/2007 09:39:40

#ifndef _FLIPTOOL_H_
#define _FLIPTOOL_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_FLIPTOOL 10031
#define SYMBOL_FLIPTOOL_STYLE 0
#define SYMBOL_FLIPTOOL_TITLE _("FlipTool")
#define SYMBOL_FLIPTOOL_IDNAME ID_FLIPTOOL
#define SYMBOL_FLIPTOOL_SIZE wxSize(200, -1)
#define SYMBOL_FLIPTOOL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * FlipTool class declaration
 */

class FlipTool: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( FlipTool )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    FlipTool();
    FlipTool( wxWindow* parent, wxWindowID id = SYMBOL_FLIPTOOL_IDNAME, const wxPoint& pos = SYMBOL_FLIPTOOL_POSITION, const wxSize& size = SYMBOL_FLIPTOOL_SIZE, long style = SYMBOL_FLIPTOOL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_FLIPTOOL_IDNAME, const wxPoint& pos = SYMBOL_FLIPTOOL_POSITION, const wxSize& size = SYMBOL_FLIPTOOL_SIZE, long style = SYMBOL_FLIPTOOL_STYLE );

    /// Destructor
    ~FlipTool();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();
	void OnFlipCoronalButtonClick( wxCommandEvent& event );
	void OnFlipAxialButtonClick( wxCommandEvent& event );
	void OnFlipSagitalButtonClick( wxCommandEvent& event );
	void OnCloseButtonClick( wxCommandEvent& event );

////@begin FlipTool event handler declarations

////@end FlipTool event handler declarations

////@begin FlipTool member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end FlipTool member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin FlipTool member variables
////@end FlipTool member variables
};

#endif
    // _FLIPTOOL_H_
