/////////////////////////////////////////////////////////////////////////////
// Name:        resampletool.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     28/08/2007 06:41:39
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 28/08/2007 06:41:39

#ifndef _RESAMPLETOOL_H_
#define _RESAMPLETOOL_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
#include "wx/spinctrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxSpinCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_RESAMPLETOOL 10035
#define SYMBOL_RESAMPLETOOL_STYLE 0
#define SYMBOL_RESAMPLETOOL_TITLE _("ResampleTool")
#define SYMBOL_RESAMPLETOOL_IDNAME ID_RESAMPLETOOL
#define SYMBOL_RESAMPLETOOL_SIZE wxSize(200, -1)
#define SYMBOL_RESAMPLETOOL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ResampleTool class declaration
 */

class ResampleTool: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( ResampleTool )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ResampleTool();
    ResampleTool( wxWindow* parent, wxWindowID id = SYMBOL_RESAMPLETOOL_IDNAME, const wxPoint& pos = SYMBOL_RESAMPLETOOL_POSITION, const wxSize& size = SYMBOL_RESAMPLETOOL_SIZE, long style = SYMBOL_RESAMPLETOOL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_RESAMPLETOOL_IDNAME, const wxPoint& pos = SYMBOL_RESAMPLETOOL_POSITION, const wxSize& size = SYMBOL_RESAMPLETOOL_SIZE, long style = SYMBOL_RESAMPLETOOL_STYLE );

    /// Destructor
    ~ResampleTool();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();
	void OnStartButtonClick( wxCommandEvent& event );
	void OnCloseButtonClick( wxCommandEvent& event );

////@begin ResampleTool event handler declarations

////@end ResampleTool event handler declarations

////@begin ResampleTool member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ResampleTool member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ResampleTool member variables
    wxSpinCtrl* mX;
    wxSpinCtrl* mY;
    wxSpinCtrl* mZ;
    wxChoice* mFilter;
////@end ResampleTool member variables
};

#endif
    // _RESAMPLETOOL_H_
