/////////////////////////////////////////////////////////////////////////////
// Name:        brushpanel.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     10/08/2007 11:53:59
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 10/08/2007 11:53:59

#ifndef _SEG3DEVENTS_H_
#define _SEG3DEVENTS_H_

/*!
 * Includes
 */

#include <wx/wx.h>

DECLARE_EVENT_TYPE(wxEVT_CURSOR_INFORMATION_CHANGE,-2)
DECLARE_EVENT_TYPE(wxEVT_BRUSH_RADIUS_CHANGE, -3)
DECLARE_EVENT_TYPE(wxEVT_CROP_SET_RANGE, -4)
DECLARE_EVENT_TYPE(wxEVT_CROP_SET_MINMAX, -5)
DECLARE_EVENT_TYPE(wxEVT_SET_PROGRESS, -6)


#endif // _SEG3DEVENTS_H_
