itcl_class SCIRun_Fields_MapFieldDataOntoNodes {
    inherit Module
    constructor {config} {
        set name MapFieldDataOntoNodes
        set_defaults
    }

    method set_defaults {} {
    }

    method ui {} {
        set w .ui[modname]
        if {[winfo exists $w]} {
            return
        }
        sci_toplevel $w
        sci_label $w.row1 -text "This GUI was auto-generated by the Component Wizard."
        sci_label $w.row2 -text {edit the file "/Users/jeroen/projects/scirun/develop2/src/Dataflow/GUI/MapFieldDataOntoNodes.tcl" to modify it.}
        pack $w.row1 $w.row2 -side top -padx 10 -pady 10

        makeSciButtonPanel $w $w $this
        moveToCursor $w
    }
}


