# -*- coding: utf-8 -*-
# generated by wxGlade 0.5 on Wed Aug  8 10:56:48 2007 from /home/scratch/mjc/cibc/SCIRun/src/StandAlone/Apps/FEMesher/wxMesher

import wx
from M3DGLCanvas import M3DGLCanvas

# begin wxGlade: dependencies
# end wxGlade

class ViewerFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ViewerFrame.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.FULL_REPAINT_ON_RESIZE|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.Viewer_statusbar = self.CreateStatusBar(2, 0)
        self.viewer_canvas = M3DGLCanvas(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade


    def __set_properties(self):
        # begin wxGlade: ViewerFrame.__set_properties
        self.SetTitle("Viewer")
        self.SetSize((800, 450))
        self.Viewer_statusbar.SetStatusWidths([-1, -1])
        # statusbar fields
        Viewer_statusbar_fields = ["Status", "FPS"]
        for i in range(len(Viewer_statusbar_fields)):
            self.Viewer_statusbar.SetStatusText(Viewer_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ViewerFrame.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(self.viewer_canvas, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_4)
        self.Layout()
        # end wxGlade

# end of class ViewerFrame


